
DROP TABLE IF EXISTS planets;
CREATE TABLE planets (
  pid int AUTO_INCREMENT  PRIMARY KEY,
  planet_name VARCHAR(50)
);
DROP TABLE IF EXISTS distances;
CREATE TABLE distances (
  did int AUTO_INCREMENT  PRIMARY KEY,
  origin_planet VARCHAR(50),
  next_planet  VARCHAR(50),
  distance DECIMAL(10,2)
);

INSERT INTO planets (planet_name) VALUES
	('A'),
	('B'),
    ('C'),
    ('D'),
    ('E'),
    ('F'),
    ('G'),
    ('H'),
    ('I'),
    ('J'),
    ('K'),
    ('L'),
    ('M'),
    ('N'),
    ('O'),
    ('P'),
    ('Q'),
    ('R'),
   ('S'),
   ('T'),
   ('U'),
    ('V'),
    ('W'),
   ('X'),
   ('Y'),
   ('Z'),
   ('A"'),
   ('B"'),
   ('C"'),
   ('D"'),
   ('E"'),
   ('F"'),
   ('G"'),
   ('H"'),
   ('I"'),
   ('J"'),
   ('K"'),
   ('L"');

   


INSERT INTO distances (origin_planet,next_planet,distance) VALUES 
('A','B',0.30),
('A','C',0.90),
('A','D',0.10),
('B','H',0.20),
('B','E',1.30),
('C','F',0.30),
('D','L',0.00),
('D','M',0.20),
('H','G',3.10),
('E','I',6.10),
('F','J',2.40),
('F','K',0.30),
('G','Z',4.00),
('I','Z',3.70),
('I','J',2.90),
('L','T',9.80),
('T','N',8.80),
('T','S',13.40),
('S','O',6.00),
('O','U',3.50),
('J','R',5.40),
('R','P',1.90),
('R','L"',0.70),
('Z','Y',3.20),
('Y','Q',20.30),
('Q','X',10.40),
('L"','X',8.10),
('X','K"',0.70),
('P','U',8.40),
('U','K"',12.30),
('U','J"',2.50),
('J"','V',3.00),
('K"','V',7.20),
('J"','I"',13.40),
('Y','A"',17.00),
('A"','B"',7.20),
('B"','C"',21.30),
('K"','W',16.00),
('W','C"',4.70),
('W','E"',33.90),
('C"','D"',30.10),
('E"','E"',7.60),
('E"','F"',34.20),
('F"','G"',2.40),
('G"','H"',1.10);
